### ISSUE TITLE
Checklist des actions avant atterissage

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1167]
- [ ] facturation des serveurs OVH (qui met la CB à la CNAM/CPAM31)
- [ ] idem compte Mailjet et autres dépendances
- [ ] accès aux serveurs PROD/Staging (en SSH pour Brice)
- [ ]  accès aux DNS/github/gitlab/passbolt...
- [ ] ne plus dépendre d'outils chez vos devops (yourlabs & co...)
- [ ] testez une procédure pour changer les mots de passe/accès aux services
- [ ] supprimez les anciens (moi compris) de contact@mrs.beta.gouv.fr, accès...
- [ ] prévenez beta.gouv.fr même si c'est fini, que vous êtes dépendants de .beta.gouv.fr et qu'il faut qu'ils gardent la redirection DNS !
- [ ] prenez bien 1 jour avec toute l'équipe pour vous assurer que vous avez la main sur le produit/service

**Comment by notmoebius** [comment]
L'idée est de rendre autonome une personne ou une équipe pour poursuivre la mission de MCO, voir de faire quelques corrections
